default: &default
  adapter: mysql2
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
production:
  <<: *default
staging:
  <<: *default
